language: ruby

services:
  - mysql

rvm:
  - 1.9.3
  - 2.0.0

env:
  - REDMINE_VER=2.2.4
  - REDMINE_VER=2.3.4
  - REDMINE_VER=2.4.3
  - REDMINE_VER=2.4.4
  - REDMINE_VER=2.4.5
  - REDMINE_VER=2.5.0
  - REDMINE_VER=2.5.1

matrix:
  exclude:
    - rvm: 2.0.0
      env: REDMINE_VER=2.2.4

branches:
  only:
    - master

before_install:
  - export PLUGIN_NAME=notify_custom_users
  - export DB=mysql
  - export REDMINE_PATH=$HOME/redmine
  - svn co http://svn.redmine.org/redmine/tags/$REDMINE_VER $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH

install:
  - bundle install

before_script:
  - rake db:create
  - rake db:migrate
  - rake redmine:plugins:migrate

script:
  - rake redmine:plugins:test NAME=$PLUGIN_NAME
